// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// example0
void example0();
RcppExport SEXP RcppCCTZ_example0() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    example0();
    return R_NilValue;
END_RCPP
}
// helloMoon
int helloMoon();
RcppExport SEXP RcppCCTZ_helloMoon() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(helloMoon());
    return __result;
END_RCPP
}
// example1
void example1();
RcppExport SEXP RcppCCTZ_example1() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    example1();
    return R_NilValue;
END_RCPP
}
// example2
int example2();
RcppExport SEXP RcppCCTZ_example2() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(example2());
    return __result;
END_RCPP
}
// example3
void example3();
RcppExport SEXP RcppCCTZ_example3() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    example3();
    return R_NilValue;
END_RCPP
}
// example4
void example4();
RcppExport SEXP RcppCCTZ_example4() {
BEGIN_RCPP
    Rcpp::RNGScope __rngScope;
    example4();
    return R_NilValue;
END_RCPP
}
